### ISSUE TITLE
Homey Energy

### ISSUE THREAD

**Issue by SmartHomeEnthusiast** [bisand/net.biseth.myenergi#53]
This seems to have appeared after recent app update. The energy tab in Homey app shows Eddi power level from Harvi and not what Eddi is actually consuming. It is dark so no solar PV and Eddi showing 2.49KW consumption. Eddi is off, waiting for surplus.

**Comment by bisand** [comment]
Hi,

Eddi measures the power usage from CT1-CT3 and uses these values for calculating the energy usage since last update. you should be able to select which CT clamp to include in your calculation on the settings page, but I see that the Eddi device is not currently honoring that setting.

I will fix that and publish a new version very soon. I do not own an Eddi device, so it would be very helpful if you are able to post an anonymized output from myenergi API. Use the following URL to get the data. https://s18.myenergi.net/cgi-jstatus-*
You will have to use the same login as you used when you installed the Homey app.

Could you also provide some information on what the different CT clamps are connected to?

Thanks!

**Comment by bisand** [comment]
I have just published a new test version. You can install it from here: https://homey.app/a/net.biseth.myenergi/test/

The total power and energy calculation is changed to honor the settings under "Advanced Settings". I would b happy if you could install the test version and report back with your findings.

Thanks!

**Comment by SmartHomeEnthusiast** [comment]
Evening, thanks for your responses. I have installed the test version and now the correct numbers are being shown again in Homey energy tab. I tried the cgi-jstatus link and the resulting page showed hardly any information. There is one CT clamp that I am aware of and, as far as I know, it is connected to the mains connection to monitor the direction and amount of electric energy

**Comment by SmartHomeEnthusiast** [comment]
CT1 shows measurements, CT 2 & 3 show nothing

**Comment by SmartHomeEnthusiast** [comment]
Interesting discovery. Several of the tag names have changed so had to amend a few flows, that's easy enough of course but can't find one to display the amount transferred today

**Comment by SmartHomeEnthusiast** [comment]
The numbers displayed in the Homey app for Energy and Energy CT1, these seem to be the same, are not what the android myenergie app shows

**Comment by SmartHomeEnthusiast** [comment]
Homey app shows 7.69kWh, whereas myEnergie app shows 3.5kWh

**Comment by SmartHomeEnthusiast** [comment]
Just looked at Insights, your app didn't reset the Energy from yesterday so it started at 4.2kWh instead of zero

**Comment by bisand** [comment]
Hi,

Not sure if I understand you correctly, but I have published a [new version](https://homey.app/a/net.biseth.myenergi/test/) that include a setting to subtract generated energy from total when performing the energy calculation. Hope that solves the discrepancy you see between myenergi app and Homey app when it comes to energy calculation.

Depending on how you choose to calculate energy, the CT1 energy and total energy can be the same. By default the system is automatically choosing which CTs chould be used in the power calculation. It selects the CT that is named "Internal Load". You can of course override this under "Advanced setings". See screenshot below:
![image](https://user-images.githubusercontent.com/376963/221494835-a3f670ef-227f-4727-a713-584043bfba83.png)
_(Note! Norwegian language in screenshot)_

Just to be clear, the Homey app does not automatically reset energy usage. You will have to do that yourself by setting the offset under "Advanced settings".

Hope this solves some of your issues mentioned above. Let me know what you think.

Thanks! :)

**Comment by SmartHomeEnthusiast** [comment]
Excellent thanks, installing now. In previous live versions their was a tag for energy transferred today, it has disappeared from recent live and test versions. This new setting looks to bring it back

**Comment by bisand** [comment]
Perfect!
Closing this issue now and will publish the newest version to production. Thanks for your feedback!

**Comment by SmartHomeEnthusiast** [comment]
Morning, this issue may not be resolved or I'm not understanding what has changed. Insights is not resetting if I manually reset the energy meters so still shows a growing accumulation. I am trying to replicate a tag that used to exist in your app for "Power transferred today", I think that's what it was called. It showed in Homey what the myenergie phone app showed for Green Energy Today that is transferred via Eddi to my hot water storage. This disappeared a couple of versions ago. There is a number tag now for Diverted Power but the number doesn't match what the myenergie system has and can't be found in Insights to see how it changes, it has been displaying 953 this morning, presuming Wh and not kWh, myenergie shows 0.7kWh.
Sorry for being a nuisance, I'm trying to get back to where I was where I my Oil Fired Boiler controlled by Homey/Tado would heat hot water for a period of time worked out based on how much energy myenergie transferred to hot water storage

**Comment by SmartHomeEnthusiast** [comment]
Morning, sorry to be a niusance but either I don't understand the changes or there is a bug/issue. I cannot manage to get your app to display energy transferred "today", it still shows cumulated since last reset, In previous versions there was a number tag for Transferred today, it has been removed, it showed the figure from the myenergie phone app for Green Energy Today. That tag would be very useful to have back again. A way to, via flows, manually reset Energy at minute after midnight might work. No sure

**Comment by SmartHomeEnthusiast** [comment]
Edit, I have created a PBTH device which should allow me to replace various tags.

**Comment by bisand** [comment]
OK, so if I understand you correctly, you want to be able to display the energy consumption of your home "today" and maybe also other periods. That is currently not supported in the Homey app, but I can implement it and hopefully retrieve the data you want from myenergi. Remember, I can only supply data that exist in the API that myenergi is providing. If I cannot find it, it's a bit tricky to implement ;)
I will do some research to see if the API is able to return what you want.

**Comment by SmartHomeEnthusiast** [comment]
Not of "home", just energy sent via Eddi to hot water. A couple versions ago of your app, it used to do this via a number tag with a name similar to Energy Transfered Today. I'm not worried about other days. I am experimenting with a Power By The Hour device that may be able to do what I need, it will take a couple of days to be sure

**Comment by SmartHomeEnthusiast** [comment]
App behaving very oddly today, the numbers being reported are not what is being measured and displayed in myEnergie phone app
![Screenshot 2023-03-05 190455](https://user-images.githubusercontent.com/102260332/222980681-0e65defa-7549-4a27-b619-ea40d1ca7540.png)
![Screenshot 2023-03-05 190938](https://user-images.githubusercontent.com/102260332/222980798-b94290bf-ffc5-4597-8462-d4aae11ebefe.png)
The Energy CT1 starts at 7.48kWh at midnight, the Energy starts at 9.94kWh but the 2 graphs basically track each other

![Screenshot 2023-03-05 191229](https://user-images.githubusercontent.com/102260332/222980897-554f067a-58f4-441a-b67c-39cd5f0c56ef.png)

**Comment by bisand** [comment]
It’s hard for me to determine what the difference between myenergi app and homey app without any data examples from myenergi app. Can you also provide a screenshot of that and pinpoint what the difference is?

CT1 and Energy will most of the time track each other because CT1 is used in the total energy calculation. It actually depend on what you have selected under «Advanced settings». If you have selected Automatic, the it will use all CTs that is named «Internal Load». If you have selected manual, then the selected CTs will be used in the calculation. It is only the Energy data that will be used by Homey when determining the total energy.

Reasons for the differences could be that CT1
‘s offset has been reset, or even multiple CTs have been used in calculation. That could lead to differences over time.

The energy for the CT clamps should only be used as a reference and will only reflect how much energy has been drawn from that particular phase.

**Comment by SmartHomeEnthusiast** [comment]
I have the app set on Automatic for the CT it uses, I haven't reset theose today, I did manually reset a couple of days ago to see if that sorted the cumulation issue.
![Screenshot_20230305-184045](https://user-images.githubusercontent.com/102260332/222981851-af76da07-e424-42fb-9c48-f91b42b723a9.png)
![Screenshot_20230305-193544](https://user-images.githubusercontent.com/102260332/222981895-c4bb8c25-8dc7-49d3-ace3-24dbc0422541.png)
I wonder are myEnergie changing/updating their api and what is published. The problem may very well be at their end

**Comment by SmartHomeEnthusiast** [comment]
The imported figure of 30.8 tracks almost perfectly with what SolarEdge are reporting was imported. Total house consumption today was 42.5kWh (we have 2 Tesla) of which 12.4kWh was produced by the solar panels and used by the home, 6.4kWh was diverted by Eddi to hot water

**Comment by bisand** [comment]
Does the data from Harvi reflect the 30.8 you see in your other devices?
The Api from myenergi is not very detailed, and I also don not have a local Eddi for testing. Hope you have some patience while I try to sort things out. A nice help would be if you also could supply the output from the following url: [https://s18.myenergi.net/cgi-jstatus-*](https://s18.myenergi.net/cgi-jstatus-*)

**Comment by bisand** [comment]
You can also try to decrease the data update interval in the app settings to see if that could improve the accuracy. Minimum value here is 5 seconds. Default is 60

**Comment by SmartHomeEnthusiast** [comment]
![Screenshot_20230305-200909](https://user-images.githubusercontent.com/102260332/222983354-f61108dd-8995-47a1-a30c-847942e8d511.png)
It does yes, the consumption figure of 42.8 subtract the Used figure of 12.4 and you get 30.4. They are rarely identical, they use their own CTs but they are usually very close.
When I go to that link nd provide login details all I get in return is
{"status":"-12","statustext":""}

**Comment by bisand** [comment]
> ![Screenshot_20230305-200909](https://user-images.githubusercontent.com/102260332/222983354-f61108dd-8995-47a1-a30c-847942e8d511.png)
> It does yes, the consumption figure of 42.8 subtract the Used figure of 12.4 and you get 30.4. They are rarely identical, they use their own CTs but they are usually very close.
> When I go to that link nd provide login details all I get in return is
> {"status":"-12","statustext":""}

Ok, you might have left out the asterisk at the end (*) Can you doubble check that the url ends with *

**Comment by SmartHomeEnthusiast** [comment]
The * is there

**Comment by bisand** [comment]
> The * is there

Ok, strange. Let me re-evaluate the logic and see if I can find any discrepancies. Meanwhile, you can monitor the data to see if you can see any patterns emerge.

**Comment by SmartHomeEnthusiast** [comment]
We had a power issue yesterday, was off for about half an hour, weird data though
![Screenshot 2023-03-07 091355](https://user-images.githubusercontent.com/102260332/223378211-5514ca12-54c7-4698-9528-0b9d87f20320.png)
That from a Power By The Hour device using data from your Homey myenergie app, it resets at midnight

![Screenshot 2023-03-07 091605](https://user-images.githubusercontent.com/102260332/223378410-3e064621-99bd-42c8-af33-bff3a36a34dd.png)
Data in Homey myenerge app, cumulative but doesn't track with the PBTH one

**Comment by SmartHomeEnthusiast** [comment]
Today so far
![Screenshot 2023-03-07 091640](https://user-images.githubusercontent.com/102260332/223378775-6dc35631-6ef4-4898-aca4-f13a2055fb35.png)
The numbers in the PBTH app match perfectly with myEnergie phone app. Yesterday there was no correlation in data at all

**Comment by SmartHomeEnthusiast** [comment]
Both those insights show the same increase today, just that PBTH started at zero

**Comment by SmartHomeEnthusiast** [comment]
Curious event, myenergie has been working grand and the PBTH app has been summarising daily production correctly.....shelly app has however been reporting
https://community.homey.app/t/app-pro-cloud-shelly/765/3750?u=philip_montgomery

**Comment by SmartHomeEnthusiast** [comment]
Curious event, this is today
![Screenshot 2023-03-12 160705](https://user-images.githubusercontent.com/102260332/224557213-3a080a4d-96cc-46c1-b28d-b6d228db8bf5.jpg)
that large spike in PBTH starts at 2am, hours before any solarPV happened. The PBTH app gets it's info from myenergie Homey app which didn't show similar rise at that time but the rise is to 43.74kWh which is what myenergie is at as it is summing data and not resetting. Both show, although it is not apparent due to vertical scale, the same increases from about 0930

**Comment by SmartHomeEnthusiast** [comment]
![Screenshot 2023-04-27 183816](https://user-images.githubusercontent.com/102260332/234944766-53bfe460-7801-4e94-80a0-df83922df890.jpg)
Since your most recent update this PBTH device is reporting incorrect data. That graph cannot start at that time of day as it based on surplus solarPV production. Same device as above

**Comment by bisand** [comment]
Closing this long-running thread as part of a housekeeping sweep — here's the summary of where each part ended up:

- **The original bug** (Energy tab showing the wrong Eddi consumption because the CT selection wasn't honored) was fixed back in February 2023 and confirmed working in this thread. That fix has been in production for a long time.
- **Energy reporting in Homey has since been reworked**: v1.11.0 added the Homey Energy Hub integration (#76), and the just-merged #91 adds per-CT power sensors and a separate configurable "House Power" CT group, which makes it much easier to see what each clamp actually measures.
- **The remaining request — energy transferred "today"** (values that reset at midnight, matching the myenergi phone app) is a real gap, and it is tracked in #57 and #82. The plan there is to use myenergi's historic data API (which provides authoritative per-hour energy figures) rather than the app's local power-integration approximation — that approximation is also what caused the drift and restart spikes reported here.

Thanks @SmartHomeEnthusiast for the thorough testing and patience back then — the daily/interval energy work will be tracked in #57 and #82.
